<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\CoreExtension;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;
use Twig\TemplateWrapper;

/* catalog/view/template/sections/home_section.twig */
class __TwigTemplate_3ee7297ed123f7fedbdaac4c07fb9393 extends Template
{
    private Source $source;
    /**
     * @var array<string, Template>
     */
    private array $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = []): iterable
    {
        $macros = $this->macros;
        // line 3
        yield "<section class=\"home-section home-section-home_section\">
  ";
        // line 4
        if (CoreExtension::getAttribute($this->env, $this->source, ($context["fields"] ?? null), "headline", [], "any", false, false, false, 4)) {
            yield "<h2>";
            yield CoreExtension::getAttribute($this->env, $this->source, ($context["fields"] ?? null), "headline", [], "any", false, false, false, 4);
            yield "</h2>";
        }
        // line 5
        yield "
  ";
        // line 7
        yield "  ";
        // line 8
        yield "
  ";
        // line 10
        yield "  ";
        // line 11
        yield "  ";
        // line 12
        yield "  ";
        // line 13
        yield "</section>
";
        yield from [];
    }

    /**
     * @codeCoverageIgnore
     */
    public function getTemplateName(): string
    {
        return "catalog/view/template/sections/home_section.twig";
    }

    /**
     * @codeCoverageIgnore
     */
    public function isTraitable(): bool
    {
        return false;
    }

    /**
     * @codeCoverageIgnore
     */
    public function getDebugInfo(): array
    {
        return array (  65 => 13,  63 => 12,  61 => 11,  59 => 10,  56 => 8,  54 => 7,  51 => 5,  45 => 4,  42 => 3,);
    }

    public function getSourceContext(): Source
    {
        return new Source("{# Auto-generated by Homepage Section Builder v2. #}
{# section_type: products #}
<section class=\"home-section home-section-home_section\">
  {% if fields.headline %}<h2>{{ fields.headline }}</h2>{% endif %}

  {# Data contract #}
  {# section, fields, items, custom_fields, custom_repeaters, products, articles, links #}

  {# Example loops #}
  {# {% for item in items %}...{% endfor %} #}
  {# {% for product in products %}...{% endfor %} #}
  {# {% for article in articles %}...{% endfor %} #}
</section>
", "catalog/view/template/sections/home_section.twig", "/Applications/MAMP/htdocs/catalog/view/template/sections/home_section.twig");
    }
}
