<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\CoreExtension;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;
use Twig\TemplateWrapper;

/* catalog/view/template/sections/haqqimizda.twig */
class __TwigTemplate_2597409e21115e079125f7d055e41fae extends Template
{
    private Source $source;
    /**
     * @var array<string, Template>
     */
    private array $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = []): iterable
    {
        $macros = $this->macros;
        // line 3
        yield "<section class=\"home-section home-section-haqqimizda\">
  <div class=\"row align-items-center g-4\">
    <div class=\"col-12 col-md-6\">
      ";
        // line 6
        if (CoreExtension::getAttribute($this->env, $this->source, ($context["fields"] ?? null), "headline", [], "any", false, false, false, 6)) {
            // line 7
            yield "        <h2>";
            yield CoreExtension::getAttribute($this->env, $this->source, ($context["fields"] ?? null), "headline", [], "any", false, false, false, 7);
            yield "</h2>
      ";
        }
        // line 9
        yield "
      ";
        // line 10
        if (CoreExtension::getAttribute($this->env, $this->source, ($context["fields"] ?? null), "description", [], "any", false, false, false, 10)) {
            // line 11
            yield "        <p>";
            yield Twig\Extension\CoreExtension::nl2br($this->env->getRuntime('Twig\Runtime\EscaperRuntime')->escape(CoreExtension::getAttribute($this->env, $this->source, ($context["fields"] ?? null), "description", [], "any", false, false, false, 11), "html", null, true));
            yield "</p>
      ";
        }
        // line 13
        yield "    </div>

    ";
        // line 15
        if (CoreExtension::getAttribute($this->env, $this->source, ($context["fields"] ?? null), "image", [], "any", false, false, false, 15)) {
            // line 16
            yield "      <div class=\"col-12 col-md-6\">
        <img src=\"image/";
            // line 17
            yield CoreExtension::getAttribute($this->env, $this->source, ($context["fields"] ?? null), "image", [], "any", false, false, false, 17);
            yield "\" alt=\"";
            yield ((CoreExtension::getAttribute($this->env, $this->source, ($context["fields"] ?? null), "headline", [], "any", false, false, false, 17)) ? (CoreExtension::getAttribute($this->env, $this->source, ($context["fields"] ?? null), "headline", [], "any", false, false, false, 17)) : ("Haqqımızda"));
            yield "\" class=\"img-fluid w-100\"/>
      </div>
    ";
        }
        // line 20
        yield "  </div>
</section>
";
        yield from [];
    }

    /**
     * @codeCoverageIgnore
     */
    public function getTemplateName(): string
    {
        return "catalog/view/template/sections/haqqimizda.twig";
    }

    /**
     * @codeCoverageIgnore
     */
    public function isTraitable(): bool
    {
        return false;
    }

    /**
     * @codeCoverageIgnore
     */
    public function getDebugInfo(): array
    {
        return array (  83 => 20,  75 => 17,  72 => 16,  70 => 15,  66 => 13,  60 => 11,  58 => 10,  55 => 9,  49 => 7,  47 => 6,  42 => 3,);
    }

    public function getSourceContext(): Source
    {
        return new Source("{# Auto-generated by Homepage Section Builder v2. #}
{# section_type: about #}
<section class=\"home-section home-section-haqqimizda\">
  <div class=\"row align-items-center g-4\">
    <div class=\"col-12 col-md-6\">
      {% if fields.headline %}
        <h2>{{ fields.headline }}</h2>
      {% endif %}

      {% if fields.description %}
        <p>{{ fields.description|nl2br }}</p>
      {% endif %}
    </div>

    {% if fields.image %}
      <div class=\"col-12 col-md-6\">
        <img src=\"image/{{ fields.image }}\" alt=\"{{ fields.headline ?: 'Haqqımızda' }}\" class=\"img-fluid w-100\"/>
      </div>
    {% endif %}
  </div>
</section>
", "catalog/view/template/sections/haqqimizda.twig", "/Applications/MAMP/htdocs/catalog/view/template/sections/haqqimizda.twig");
    }
}
